# Generated by Django 5.1.3 on 2024-11-06 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'inventario_producto',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField()),
                ('cantidad_vendida', models.IntegerField()),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('tienda_origen', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ventas_venta',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.IntegerField()),
                ('ubicacion_tienda', models.CharField(max_length=255)),
                ('estado_stock', models.CharField(max_length=50)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='ventas.producto')),
            ],
            options={
                'db_table': 'inventario_inventario',
            },
        ),
    ]
